/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface SchematicDatepicker {
    'altFormat': string;
    'altInput': boolean;
    'culture': string;
    'dateFormat': string;
    'defaultDate': string;
    'enableTime': boolean;
    'input': string;
  }
  interface SchematicDatepickerAttributes extends StencilHTMLAttributes {
    'altFormat'?: string;
    'altInput'?: boolean;
    'culture'?: string;
    'dateFormat'?: string;
    'defaultDate'?: string;
    'enableTime'?: boolean;
    'input'?: string;
  }

  interface SchematicFieldset {
    'selected': boolean;
    'tabs': string;
  }
  interface SchematicFieldsetAttributes extends StencilHTMLAttributes {
    'selected'?: boolean;
    'tabs'?: string;
  }

  interface SchematicImageUploader {
    'accept': string;
    'alt': string;
    'base': string;
    'container': string;
    'culture': string;
    'delete': string;
    'deleteInput': string;
    'fileName': string;
    'formDataName': string;
    'headers': string;
    'input': string;
    'maxFiles': number;
    'method': string;
    'nodrop': boolean;
    'path': string;
    'target': string;
  }
  interface SchematicImageUploaderAttributes extends StencilHTMLAttributes {
    'accept'?: string;
    'alt'?: string;
    'base'?: string;
    'container'?: string;
    'culture'?: string;
    'delete'?: string;
    'deleteInput'?: string;
    'fileName'?: string;
    'formDataName'?: string;
    'headers'?: string;
    'input'?: string;
    'maxFiles'?: number;
    'method'?: string;
    'nodrop'?: boolean;
    'path'?: string;
    'target'?: string;
  }

  interface SchematicLanguageButton {
    'base': string;
    'code': string;
    'setHref': () => void;
    'text': string;
  }
  interface SchematicLanguageButtonAttributes extends StencilHTMLAttributes {
    'base'?: string;
    'code'?: string;
    'onToggleLanguageMenu'?: (event: CustomEvent) => void;
    'text'?: string;
  }

  interface SchematicLanguageSwitcher {}
  interface SchematicLanguageSwitcherAttributes extends StencilHTMLAttributes {}

  interface SchematicLoading {}
  interface SchematicLoadingAttributes extends StencilHTMLAttributes {}

  interface SchematicQuillEditor {
    'bounds': HTMLElement | string;
    'content': string;
    'format': 'object' | 'html' | 'text' | 'json';
    'formats': string[];
    'input': string;
    'modules': { [index: string]: Object };
    'output': 'html' | 'text' | 'json';
    'placeholder': string;
    'readOnly': boolean;
    'strict': boolean;
    'styles': any;
    'theme': string;
  }
  interface SchematicQuillEditorAttributes extends StencilHTMLAttributes {
    'bounds'?: HTMLElement | string;
    'content'?: string;
    'format'?: 'object' | 'html' | 'text' | 'json';
    'formats'?: string[];
    'input'?: string;
    'modules'?: { [index: string]: Object };
    'onOnContentChanged'?: (event: CustomEvent<{
      editor: any,
      content: any,
      text: string,
      html: string,
      delta: any,
      oldDelta: any,
      source: string
    }>) => void;
    'onOnInitialised'?: (event: CustomEvent<any>) => void;
    'onOnSelectionChanged'?: (event: CustomEvent<{
      editor: any,
      range: any,
      oldRange: any,
      source: string
    }>) => void;
    'output'?: 'html' | 'text' | 'json';
    'placeholder'?: string;
    'readOnly'?: boolean;
    'strict'?: boolean;
    'styles'?: any;
    'theme'?: string;
  }

  interface SchematicResourceButtonCreate {
    'completed': string;
    'inProgress': string;
  }
  interface SchematicResourceButtonCreateAttributes extends StencilHTMLAttributes {
    'completed'?: string;
    'inProgress'?: string;
    'onCreateNewResource'?: (event: CustomEvent) => void;
  }

  interface SchematicResourceButtonDelete {
    'completed': string;
    'confirm': string;
    'inProgress': string;
  }
  interface SchematicResourceButtonDeleteAttributes extends StencilHTMLAttributes {
    'completed'?: string;
    'confirm'?: string;
    'inProgress'?: string;
    'onDeleteCurrentResouce'?: (event: CustomEvent) => void;
  }

  interface SchematicResourceButtonNew {
    'completed': string;
    'inProgress': string;
  }
  interface SchematicResourceButtonNewAttributes extends StencilHTMLAttributes {
    'completed'?: string;
    'inProgress'?: string;
    'onGetNewResource'?: (event: CustomEvent) => void;
  }

  interface SchematicResourceButtonOrder {
    'completed': string;
    'inProgress': string;
  }
  interface SchematicResourceButtonOrderAttributes extends StencilHTMLAttributes {
    'completed'?: string;
    'inProgress'?: string;
    'onOrderResources'?: (event: CustomEvent) => void;
  }

  interface SchematicResourceButtonSave {
    'completed': string;
    'inProgress': string;
  }
  interface SchematicResourceButtonSaveAttributes extends StencilHTMLAttributes {
    'completed'?: string;
    'inProgress'?: string;
    'onUpdateCurrentResource'?: (event: CustomEvent) => void;
  }

  interface SchematicResourceEditorStatus {
    'message': string;
    'status': string;
  }
  interface SchematicResourceEditorStatusAttributes extends StencilHTMLAttributes {
    'message'?: string;
    'status'?: string;
  }

  interface SchematicResourceEditorToolbar {}
  interface SchematicResourceEditorToolbarAttributes extends StencilHTMLAttributes {}

  interface SchematicResourceEditor {
    'clearEditor': () => void;
    'createResource': (messageOnComplete: string) => void;
    'deleteResource': (id: string, messageOnComplete: string) => void;
    'facets': string;
    'newResource': (messageOnComplete: string) => void;
    'noContent': string;
    'placeholder': string;
    'readCompleted': string;
    'readInProgress': string;
    'readResource': (id: string, messageOnComplete: string) => void;
    'resourceId': string;
    'updateResource': (id: string, messageOnComplete: string) => void;
    'url': string;
  }
  interface SchematicResourceEditorAttributes extends StencilHTMLAttributes {
    'facets'?: string;
    'noContent'?: string;
    'onResourceRefresh'?: (event: CustomEvent) => void;
    'onResourceUpdated'?: (event: CustomEvent) => void;
    'placeholder'?: string;
    'readCompleted'?: string;
    'readInProgress'?: string;
    'resourceId'?: string;
    'url'?: string;
  }

  interface SchematicResourceExplorer {}
  interface SchematicResourceExplorerAttributes extends StencilHTMLAttributes {
    'onUrlUpdated'?: (event: CustomEvent) => void;
  }

  interface SchematicResourceFilterControls {
    'active': boolean;
    'filtersOff': string;
    'filtersOn': string;
    'removeFilters': string;
  }
  interface SchematicResourceFilterControlsAttributes extends StencilHTMLAttributes {
    'active'?: boolean;
    'filtersOff'?: string;
    'filtersOn'?: string;
    'onFilterMenuToggle'?: (event: CustomEvent) => void;
    'onFilterStatusUpdate'?: (event: CustomEvent) => void;
    'removeFilters'?: string;
  }

  interface SchematicResourceFilters {
    'active': boolean;
    'filter': string;
    'getFilters': (url: string) => void;
    'listResources': () => void;
    'menuOpen': boolean;
    'resetFilters': string;
    'url': string;
  }
  interface SchematicResourceFiltersAttributes extends StencilHTMLAttributes {
    'active'?: boolean;
    'filter'?: string;
    'menuOpen'?: boolean;
    'onFilterMenuToggle'?: (event: CustomEvent) => void;
    'onFilterStatusUpdate'?: (event: CustomEvent) => void;
    'resetFilters'?: string;
    'url'?: string;
  }

  interface SchematicResourceListLink {
    'resourceId': string;
    'status': string;
  }
  interface SchematicResourceListLinkAttributes extends StencilHTMLAttributes {
    'onActiveResourceSet'?: (event: CustomEvent) => void;
    'resourceId'?: string;
    'status'?: string;
  }

  interface SchematicResourceList {
    'activeResourceId': string;
    'clearResourceList': () => void;
    'facets': string;
    'listResources': (url: string) => void;
    'newResource': () => void;
    'noContent': string;
    'url': string;
  }
  interface SchematicResourceListAttributes extends StencilHTMLAttributes {
    'activeResourceId'?: string;
    'facets'?: string;
    'noContent'?: string;
    'onActiveResourceSet'?: (event: CustomEvent) => void;
    'url'?: string;
  }

  interface SchematicResourceNavigator {
    'hasFilters': boolean;
    'hasSearch': boolean;
  }
  interface SchematicResourceNavigatorAttributes extends StencilHTMLAttributes {
    'hasFilters'?: boolean;
    'hasSearch'?: boolean;
  }

  interface SchematicResourceOrder {
    'culture': string;
    'facets': string;
    'url': string;
  }
  interface SchematicResourceOrderAttributes extends StencilHTMLAttributes {
    'culture'?: string;
    'facets'?: string;
    'onResourceOrderClose'?: (event: CustomEvent) => void;
    'onResourceOrderSubmit'?: (event: CustomEvent) => void;
    'url'?: string;
  }

  interface SchematicResourceRepeaterDelete {}
  interface SchematicResourceRepeaterDeleteAttributes extends StencilHTMLAttributes {
    'onDeleteRepeatable'?: (event: CustomEvent) => void;
  }

  interface SchematicResourceRepeatable {
    'deleteButton': string;
    'index': string;
    'isRequired': boolean;
    'model': string;
  }
  interface SchematicResourceRepeatableAttributes extends StencilHTMLAttributes {
    'deleteButton'?: string;
    'index'?: string;
    'isRequired'?: boolean;
    'model'?: string;
    'onResourceRepeated'?: (event: CustomEvent) => void;
  }

  interface SchematicResourceRepeaterButton {
    'text': string;
    'url': string;
  }
  interface SchematicResourceRepeaterButtonAttributes extends StencilHTMLAttributes {
    'text'?: string;
    'url'?: string;
  }

  interface SchematicResourceRepeater {
    'minInstances': number;
    'sequenceRepeatables': () => void;
  }
  interface SchematicResourceRepeaterAttributes extends StencilHTMLAttributes {
    'minInstances'?: number;
  }

  interface SchematicResourceSearch {
    'placeholder': string;
    'url': string;
    'value': string;
  }
  interface SchematicResourceSearchAttributes extends StencilHTMLAttributes {
    'placeholder'?: string;
    'url'?: string;
    'value'?: string;
  }

  interface SchematicResourceTitle {}
  interface SchematicResourceTitleAttributes extends StencilHTMLAttributes {
    'onNewResourceTitle'?: (event: CustomEvent) => void;
  }

  interface SchematicRouter {}
  interface SchematicRouterAttributes extends StencilHTMLAttributes {}

  interface SchematicSelectItem {
    'tabIndex': number;
    'value': string;
  }
  interface SchematicSelectItemAttributes extends StencilHTMLAttributes {
    'onItemSelected'?: (event: CustomEvent) => void;
    'tabIndex'?: number;
    'value'?: string;
  }

  interface SchematicSelectSearch {
    'placeholder': string;
    'url': string;
  }
  interface SchematicSelectSearchAttributes extends StencilHTMLAttributes {
    'placeholder'?: string;
    'url'?: string;
  }

  interface SchematicSignIn {
    'forgot': string;
    'mode': string;
    'return': string;
    'token': string;
    'url': string;
  }
  interface SchematicSignInAttributes extends StencilHTMLAttributes {
    'forgot'?: string;
    'mode'?: string;
    'return'?: string;
    'token'?: string;
    'url'?: string;
  }

  interface SchematicTabs {
    'name': string;
  }
  interface SchematicTabsAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface SchematicUploader {
    'accept': string;
    'culture': string;
    'formDataName': string;
    'headers': string;
    'maxFiles': number;
    'method': string;
    'nodrop': boolean;
    'target': string;
  }
  interface SchematicUploaderAttributes extends StencilHTMLAttributes {
    'accept'?: string;
    'culture'?: string;
    'formDataName'?: string;
    'headers'?: string;
    'maxFiles'?: number;
    'method'?: string;
    'nodrop'?: boolean;
    'onUploadResult'?: (event: CustomEvent) => void;
    'target'?: string;
  }

  interface SchematicUserInviteLink {
    'link': string;
    'success': string;
    'text': string;
    'url': string;
    'userId': string;
  }
  interface SchematicUserInviteLinkAttributes extends StencilHTMLAttributes {
    'link'?: string;
    'success'?: string;
    'text'?: string;
    'url'?: string;
    'userId'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'SchematicDatepicker': Components.SchematicDatepicker;
    'SchematicFieldset': Components.SchematicFieldset;
    'SchematicImageUploader': Components.SchematicImageUploader;
    'SchematicLanguageButton': Components.SchematicLanguageButton;
    'SchematicLanguageSwitcher': Components.SchematicLanguageSwitcher;
    'SchematicLoading': Components.SchematicLoading;
    'SchematicQuillEditor': Components.SchematicQuillEditor;
    'SchematicResourceButtonCreate': Components.SchematicResourceButtonCreate;
    'SchematicResourceButtonDelete': Components.SchematicResourceButtonDelete;
    'SchematicResourceButtonNew': Components.SchematicResourceButtonNew;
    'SchematicResourceButtonOrder': Components.SchematicResourceButtonOrder;
    'SchematicResourceButtonSave': Components.SchematicResourceButtonSave;
    'SchematicResourceEditorStatus': Components.SchematicResourceEditorStatus;
    'SchematicResourceEditorToolbar': Components.SchematicResourceEditorToolbar;
    'SchematicResourceEditor': Components.SchematicResourceEditor;
    'SchematicResourceExplorer': Components.SchematicResourceExplorer;
    'SchematicResourceFilterControls': Components.SchematicResourceFilterControls;
    'SchematicResourceFilters': Components.SchematicResourceFilters;
    'SchematicResourceListLink': Components.SchematicResourceListLink;
    'SchematicResourceList': Components.SchematicResourceList;
    'SchematicResourceNavigator': Components.SchematicResourceNavigator;
    'SchematicResourceOrder': Components.SchematicResourceOrder;
    'SchematicResourceRepeaterDelete': Components.SchematicResourceRepeaterDelete;
    'SchematicResourceRepeatable': Components.SchematicResourceRepeatable;
    'SchematicResourceRepeaterButton': Components.SchematicResourceRepeaterButton;
    'SchematicResourceRepeater': Components.SchematicResourceRepeater;
    'SchematicResourceSearch': Components.SchematicResourceSearch;
    'SchematicResourceTitle': Components.SchematicResourceTitle;
    'SchematicRouter': Components.SchematicRouter;
    'SchematicSelectItem': Components.SchematicSelectItem;
    'SchematicSelectSearch': Components.SchematicSelectSearch;
    'SchematicSignIn': Components.SchematicSignIn;
    'SchematicTabs': Components.SchematicTabs;
    'SchematicUploader': Components.SchematicUploader;
    'SchematicUserInviteLink': Components.SchematicUserInviteLink;
  }

  interface StencilIntrinsicElements {
    'schematic-datepicker': Components.SchematicDatepickerAttributes;
    'schematic-fieldset': Components.SchematicFieldsetAttributes;
    'schematic-image-uploader': Components.SchematicImageUploaderAttributes;
    'schematic-language-button': Components.SchematicLanguageButtonAttributes;
    'schematic-language-switcher': Components.SchematicLanguageSwitcherAttributes;
    'schematic-loading': Components.SchematicLoadingAttributes;
    'schematic-quill-editor': Components.SchematicQuillEditorAttributes;
    'schematic-resource-button-create': Components.SchematicResourceButtonCreateAttributes;
    'schematic-resource-button-delete': Components.SchematicResourceButtonDeleteAttributes;
    'schematic-resource-button-new': Components.SchematicResourceButtonNewAttributes;
    'schematic-resource-button-order': Components.SchematicResourceButtonOrderAttributes;
    'schematic-resource-button-save': Components.SchematicResourceButtonSaveAttributes;
    'schematic-resource-editor-status': Components.SchematicResourceEditorStatusAttributes;
    'schematic-resource-editor-toolbar': Components.SchematicResourceEditorToolbarAttributes;
    'schematic-resource-editor': Components.SchematicResourceEditorAttributes;
    'schematic-resource-explorer': Components.SchematicResourceExplorerAttributes;
    'schematic-resource-filter-controls': Components.SchematicResourceFilterControlsAttributes;
    'schematic-resource-filters': Components.SchematicResourceFiltersAttributes;
    'schematic-resource-list-link': Components.SchematicResourceListLinkAttributes;
    'schematic-resource-list': Components.SchematicResourceListAttributes;
    'schematic-resource-navigator': Components.SchematicResourceNavigatorAttributes;
    'schematic-resource-order': Components.SchematicResourceOrderAttributes;
    'schematic-resource-repeater-delete': Components.SchematicResourceRepeaterDeleteAttributes;
    'schematic-resource-repeatable': Components.SchematicResourceRepeatableAttributes;
    'schematic-resource-repeater-button': Components.SchematicResourceRepeaterButtonAttributes;
    'schematic-resource-repeater': Components.SchematicResourceRepeaterAttributes;
    'schematic-resource-search': Components.SchematicResourceSearchAttributes;
    'schematic-resource-title': Components.SchematicResourceTitleAttributes;
    'schematic-router': Components.SchematicRouterAttributes;
    'schematic-select-item': Components.SchematicSelectItemAttributes;
    'schematic-select-search': Components.SchematicSelectSearchAttributes;
    'schematic-sign-in': Components.SchematicSignInAttributes;
    'schematic-tabs': Components.SchematicTabsAttributes;
    'schematic-uploader': Components.SchematicUploaderAttributes;
    'schematic-user-invite-link': Components.SchematicUserInviteLinkAttributes;
  }


  interface HTMLSchematicDatepickerElement extends Components.SchematicDatepicker, HTMLStencilElement {}
  var HTMLSchematicDatepickerElement: {
    prototype: HTMLSchematicDatepickerElement;
    new (): HTMLSchematicDatepickerElement;
  };

  interface HTMLSchematicFieldsetElement extends Components.SchematicFieldset, HTMLStencilElement {}
  var HTMLSchematicFieldsetElement: {
    prototype: HTMLSchematicFieldsetElement;
    new (): HTMLSchematicFieldsetElement;
  };

  interface HTMLSchematicImageUploaderElement extends Components.SchematicImageUploader, HTMLStencilElement {}
  var HTMLSchematicImageUploaderElement: {
    prototype: HTMLSchematicImageUploaderElement;
    new (): HTMLSchematicImageUploaderElement;
  };

  interface HTMLSchematicLanguageButtonElement extends Components.SchematicLanguageButton, HTMLStencilElement {}
  var HTMLSchematicLanguageButtonElement: {
    prototype: HTMLSchematicLanguageButtonElement;
    new (): HTMLSchematicLanguageButtonElement;
  };

  interface HTMLSchematicLanguageSwitcherElement extends Components.SchematicLanguageSwitcher, HTMLStencilElement {}
  var HTMLSchematicLanguageSwitcherElement: {
    prototype: HTMLSchematicLanguageSwitcherElement;
    new (): HTMLSchematicLanguageSwitcherElement;
  };

  interface HTMLSchematicLoadingElement extends Components.SchematicLoading, HTMLStencilElement {}
  var HTMLSchematicLoadingElement: {
    prototype: HTMLSchematicLoadingElement;
    new (): HTMLSchematicLoadingElement;
  };

  interface HTMLSchematicQuillEditorElement extends Components.SchematicQuillEditor, HTMLStencilElement {}
  var HTMLSchematicQuillEditorElement: {
    prototype: HTMLSchematicQuillEditorElement;
    new (): HTMLSchematicQuillEditorElement;
  };

  interface HTMLSchematicResourceButtonCreateElement extends Components.SchematicResourceButtonCreate, HTMLStencilElement {}
  var HTMLSchematicResourceButtonCreateElement: {
    prototype: HTMLSchematicResourceButtonCreateElement;
    new (): HTMLSchematicResourceButtonCreateElement;
  };

  interface HTMLSchematicResourceButtonDeleteElement extends Components.SchematicResourceButtonDelete, HTMLStencilElement {}
  var HTMLSchematicResourceButtonDeleteElement: {
    prototype: HTMLSchematicResourceButtonDeleteElement;
    new (): HTMLSchematicResourceButtonDeleteElement;
  };

  interface HTMLSchematicResourceButtonNewElement extends Components.SchematicResourceButtonNew, HTMLStencilElement {}
  var HTMLSchematicResourceButtonNewElement: {
    prototype: HTMLSchematicResourceButtonNewElement;
    new (): HTMLSchematicResourceButtonNewElement;
  };

  interface HTMLSchematicResourceButtonOrderElement extends Components.SchematicResourceButtonOrder, HTMLStencilElement {}
  var HTMLSchematicResourceButtonOrderElement: {
    prototype: HTMLSchematicResourceButtonOrderElement;
    new (): HTMLSchematicResourceButtonOrderElement;
  };

  interface HTMLSchematicResourceButtonSaveElement extends Components.SchematicResourceButtonSave, HTMLStencilElement {}
  var HTMLSchematicResourceButtonSaveElement: {
    prototype: HTMLSchematicResourceButtonSaveElement;
    new (): HTMLSchematicResourceButtonSaveElement;
  };

  interface HTMLSchematicResourceEditorStatusElement extends Components.SchematicResourceEditorStatus, HTMLStencilElement {}
  var HTMLSchematicResourceEditorStatusElement: {
    prototype: HTMLSchematicResourceEditorStatusElement;
    new (): HTMLSchematicResourceEditorStatusElement;
  };

  interface HTMLSchematicResourceEditorToolbarElement extends Components.SchematicResourceEditorToolbar, HTMLStencilElement {}
  var HTMLSchematicResourceEditorToolbarElement: {
    prototype: HTMLSchematicResourceEditorToolbarElement;
    new (): HTMLSchematicResourceEditorToolbarElement;
  };

  interface HTMLSchematicResourceEditorElement extends Components.SchematicResourceEditor, HTMLStencilElement {}
  var HTMLSchematicResourceEditorElement: {
    prototype: HTMLSchematicResourceEditorElement;
    new (): HTMLSchematicResourceEditorElement;
  };

  interface HTMLSchematicResourceExplorerElement extends Components.SchematicResourceExplorer, HTMLStencilElement {}
  var HTMLSchematicResourceExplorerElement: {
    prototype: HTMLSchematicResourceExplorerElement;
    new (): HTMLSchematicResourceExplorerElement;
  };

  interface HTMLSchematicResourceFilterControlsElement extends Components.SchematicResourceFilterControls, HTMLStencilElement {}
  var HTMLSchematicResourceFilterControlsElement: {
    prototype: HTMLSchematicResourceFilterControlsElement;
    new (): HTMLSchematicResourceFilterControlsElement;
  };

  interface HTMLSchematicResourceFiltersElement extends Components.SchematicResourceFilters, HTMLStencilElement {}
  var HTMLSchematicResourceFiltersElement: {
    prototype: HTMLSchematicResourceFiltersElement;
    new (): HTMLSchematicResourceFiltersElement;
  };

  interface HTMLSchematicResourceListLinkElement extends Components.SchematicResourceListLink, HTMLStencilElement {}
  var HTMLSchematicResourceListLinkElement: {
    prototype: HTMLSchematicResourceListLinkElement;
    new (): HTMLSchematicResourceListLinkElement;
  };

  interface HTMLSchematicResourceListElement extends Components.SchematicResourceList, HTMLStencilElement {}
  var HTMLSchematicResourceListElement: {
    prototype: HTMLSchematicResourceListElement;
    new (): HTMLSchematicResourceListElement;
  };

  interface HTMLSchematicResourceNavigatorElement extends Components.SchematicResourceNavigator, HTMLStencilElement {}
  var HTMLSchematicResourceNavigatorElement: {
    prototype: HTMLSchematicResourceNavigatorElement;
    new (): HTMLSchematicResourceNavigatorElement;
  };

  interface HTMLSchematicResourceOrderElement extends Components.SchematicResourceOrder, HTMLStencilElement {}
  var HTMLSchematicResourceOrderElement: {
    prototype: HTMLSchematicResourceOrderElement;
    new (): HTMLSchematicResourceOrderElement;
  };

  interface HTMLSchematicResourceRepeaterDeleteElement extends Components.SchematicResourceRepeaterDelete, HTMLStencilElement {}
  var HTMLSchematicResourceRepeaterDeleteElement: {
    prototype: HTMLSchematicResourceRepeaterDeleteElement;
    new (): HTMLSchematicResourceRepeaterDeleteElement;
  };

  interface HTMLSchematicResourceRepeatableElement extends Components.SchematicResourceRepeatable, HTMLStencilElement {}
  var HTMLSchematicResourceRepeatableElement: {
    prototype: HTMLSchematicResourceRepeatableElement;
    new (): HTMLSchematicResourceRepeatableElement;
  };

  interface HTMLSchematicResourceRepeaterButtonElement extends Components.SchematicResourceRepeaterButton, HTMLStencilElement {}
  var HTMLSchematicResourceRepeaterButtonElement: {
    prototype: HTMLSchematicResourceRepeaterButtonElement;
    new (): HTMLSchematicResourceRepeaterButtonElement;
  };

  interface HTMLSchematicResourceRepeaterElement extends Components.SchematicResourceRepeater, HTMLStencilElement {}
  var HTMLSchematicResourceRepeaterElement: {
    prototype: HTMLSchematicResourceRepeaterElement;
    new (): HTMLSchematicResourceRepeaterElement;
  };

  interface HTMLSchematicResourceSearchElement extends Components.SchematicResourceSearch, HTMLStencilElement {}
  var HTMLSchematicResourceSearchElement: {
    prototype: HTMLSchematicResourceSearchElement;
    new (): HTMLSchematicResourceSearchElement;
  };

  interface HTMLSchematicResourceTitleElement extends Components.SchematicResourceTitle, HTMLStencilElement {}
  var HTMLSchematicResourceTitleElement: {
    prototype: HTMLSchematicResourceTitleElement;
    new (): HTMLSchematicResourceTitleElement;
  };

  interface HTMLSchematicRouterElement extends Components.SchematicRouter, HTMLStencilElement {}
  var HTMLSchematicRouterElement: {
    prototype: HTMLSchematicRouterElement;
    new (): HTMLSchematicRouterElement;
  };

  interface HTMLSchematicSelectItemElement extends Components.SchematicSelectItem, HTMLStencilElement {}
  var HTMLSchematicSelectItemElement: {
    prototype: HTMLSchematicSelectItemElement;
    new (): HTMLSchematicSelectItemElement;
  };

  interface HTMLSchematicSelectSearchElement extends Components.SchematicSelectSearch, HTMLStencilElement {}
  var HTMLSchematicSelectSearchElement: {
    prototype: HTMLSchematicSelectSearchElement;
    new (): HTMLSchematicSelectSearchElement;
  };

  interface HTMLSchematicSignInElement extends Components.SchematicSignIn, HTMLStencilElement {}
  var HTMLSchematicSignInElement: {
    prototype: HTMLSchematicSignInElement;
    new (): HTMLSchematicSignInElement;
  };

  interface HTMLSchematicTabsElement extends Components.SchematicTabs, HTMLStencilElement {}
  var HTMLSchematicTabsElement: {
    prototype: HTMLSchematicTabsElement;
    new (): HTMLSchematicTabsElement;
  };

  interface HTMLSchematicUploaderElement extends Components.SchematicUploader, HTMLStencilElement {}
  var HTMLSchematicUploaderElement: {
    prototype: HTMLSchematicUploaderElement;
    new (): HTMLSchematicUploaderElement;
  };

  interface HTMLSchematicUserInviteLinkElement extends Components.SchematicUserInviteLink, HTMLStencilElement {}
  var HTMLSchematicUserInviteLinkElement: {
    prototype: HTMLSchematicUserInviteLinkElement;
    new (): HTMLSchematicUserInviteLinkElement;
  };

  interface HTMLElementTagNameMap {
    'schematic-datepicker': HTMLSchematicDatepickerElement
    'schematic-fieldset': HTMLSchematicFieldsetElement
    'schematic-image-uploader': HTMLSchematicImageUploaderElement
    'schematic-language-button': HTMLSchematicLanguageButtonElement
    'schematic-language-switcher': HTMLSchematicLanguageSwitcherElement
    'schematic-loading': HTMLSchematicLoadingElement
    'schematic-quill-editor': HTMLSchematicQuillEditorElement
    'schematic-resource-button-create': HTMLSchematicResourceButtonCreateElement
    'schematic-resource-button-delete': HTMLSchematicResourceButtonDeleteElement
    'schematic-resource-button-new': HTMLSchematicResourceButtonNewElement
    'schematic-resource-button-order': HTMLSchematicResourceButtonOrderElement
    'schematic-resource-button-save': HTMLSchematicResourceButtonSaveElement
    'schematic-resource-editor-status': HTMLSchematicResourceEditorStatusElement
    'schematic-resource-editor-toolbar': HTMLSchematicResourceEditorToolbarElement
    'schematic-resource-editor': HTMLSchematicResourceEditorElement
    'schematic-resource-explorer': HTMLSchematicResourceExplorerElement
    'schematic-resource-filter-controls': HTMLSchematicResourceFilterControlsElement
    'schematic-resource-filters': HTMLSchematicResourceFiltersElement
    'schematic-resource-list-link': HTMLSchematicResourceListLinkElement
    'schematic-resource-list': HTMLSchematicResourceListElement
    'schematic-resource-navigator': HTMLSchematicResourceNavigatorElement
    'schematic-resource-order': HTMLSchematicResourceOrderElement
    'schematic-resource-repeater-delete': HTMLSchematicResourceRepeaterDeleteElement
    'schematic-resource-repeatable': HTMLSchematicResourceRepeatableElement
    'schematic-resource-repeater-button': HTMLSchematicResourceRepeaterButtonElement
    'schematic-resource-repeater': HTMLSchematicResourceRepeaterElement
    'schematic-resource-search': HTMLSchematicResourceSearchElement
    'schematic-resource-title': HTMLSchematicResourceTitleElement
    'schematic-router': HTMLSchematicRouterElement
    'schematic-select-item': HTMLSchematicSelectItemElement
    'schematic-select-search': HTMLSchematicSelectSearchElement
    'schematic-sign-in': HTMLSchematicSignInElement
    'schematic-tabs': HTMLSchematicTabsElement
    'schematic-uploader': HTMLSchematicUploaderElement
    'schematic-user-invite-link': HTMLSchematicUserInviteLinkElement
  }

  interface ElementTagNameMap {
    'schematic-datepicker': HTMLSchematicDatepickerElement;
    'schematic-fieldset': HTMLSchematicFieldsetElement;
    'schematic-image-uploader': HTMLSchematicImageUploaderElement;
    'schematic-language-button': HTMLSchematicLanguageButtonElement;
    'schematic-language-switcher': HTMLSchematicLanguageSwitcherElement;
    'schematic-loading': HTMLSchematicLoadingElement;
    'schematic-quill-editor': HTMLSchematicQuillEditorElement;
    'schematic-resource-button-create': HTMLSchematicResourceButtonCreateElement;
    'schematic-resource-button-delete': HTMLSchematicResourceButtonDeleteElement;
    'schematic-resource-button-new': HTMLSchematicResourceButtonNewElement;
    'schematic-resource-button-order': HTMLSchematicResourceButtonOrderElement;
    'schematic-resource-button-save': HTMLSchematicResourceButtonSaveElement;
    'schematic-resource-editor-status': HTMLSchematicResourceEditorStatusElement;
    'schematic-resource-editor-toolbar': HTMLSchematicResourceEditorToolbarElement;
    'schematic-resource-editor': HTMLSchematicResourceEditorElement;
    'schematic-resource-explorer': HTMLSchematicResourceExplorerElement;
    'schematic-resource-filter-controls': HTMLSchematicResourceFilterControlsElement;
    'schematic-resource-filters': HTMLSchematicResourceFiltersElement;
    'schematic-resource-list-link': HTMLSchematicResourceListLinkElement;
    'schematic-resource-list': HTMLSchematicResourceListElement;
    'schematic-resource-navigator': HTMLSchematicResourceNavigatorElement;
    'schematic-resource-order': HTMLSchematicResourceOrderElement;
    'schematic-resource-repeater-delete': HTMLSchematicResourceRepeaterDeleteElement;
    'schematic-resource-repeatable': HTMLSchematicResourceRepeatableElement;
    'schematic-resource-repeater-button': HTMLSchematicResourceRepeaterButtonElement;
    'schematic-resource-repeater': HTMLSchematicResourceRepeaterElement;
    'schematic-resource-search': HTMLSchematicResourceSearchElement;
    'schematic-resource-title': HTMLSchematicResourceTitleElement;
    'schematic-router': HTMLSchematicRouterElement;
    'schematic-select-item': HTMLSchematicSelectItemElement;
    'schematic-select-search': HTMLSchematicSelectSearchElement;
    'schematic-sign-in': HTMLSchematicSignInElement;
    'schematic-tabs': HTMLSchematicTabsElement;
    'schematic-uploader': HTMLSchematicUploaderElement;
    'schematic-user-invite-link': HTMLSchematicUserInviteLinkElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
